version: "3"

services:
  exosuite-users-api-documentation:
    build:
      context: .
    networks:
      - documentation:
          ipv4_address: 172.42.0.2
networks:
  documentation:
    ipam:
      config:
        - subnet: 172.42.0.0/24